AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7.0
  Exclude:
    - spec/fixtures/**/*

Style/RegexpLiteral:
  EnforcedStyle: slashes
  AllowInnerSlashes: true

Style/Documentation:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true
  EnforcedStyle: no_space

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true
