name: Ruby
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.2', '3.0', '2.7']
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Build and test with Rake
        run: |
          gem install bundler undercover --no-doc
          bundle install --jobs 4 --retry 3
          bundle exec rake
      - name: undercover (local)
        run: |
          git fetch origin master:master
          undercover --compare master
      - uses: actions/upload-artifact@v2
        with:
          name: undercover.lcov
          path: coverage/lcov/undercover.lcov
  coverage:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: undercover.lcov
      - name: Upload coverage
        run: |
          ruby -e "$(curl -s https://undercover-ci.com/uploader.rb)" -- \
            --repo grodowski/undercover \
            --commit $GITHUB_SHA \
            --lcov /home/runner/work/undercover/undercover/undercover.lcov
